version: "3.9"
services:
  cats-simple-service:
    image: "cats-simple-service:0.0.1"
    ports:
      - "8931:8080"

  zio-simple-service:
    image: "zio-simple-service:0.0.1"
    ports:
      - "8932:8080"

  request-spammer-service:
    image: "request-spammer-service:0.0.1"
